### ISSUE TITLE
Docker install

### ISSUE THREAD

**Issue by grigoty** [EtokonE/Licence_Plate_Recognition#2]
After docker run have error:

```
Downloading: "https://github.com/ultralytics/yolov5/archive/master.zip" to /home/lpr/.cache/torch/hub/master.zip
Traceback (most recent call last):
  File "/home/lpr/License_Plate_Recognition/app.py", line 23, in <module>
    YoloV5 = load_yolo(weights='./models/best.pt', device=device)
  File "/home/lpr/License_Plate_Recognition/src/models/load_functions.py", line 8, in load_yolo
    yolo = torch.hub.load('ultralytics/yolov5', 'custom', path=weights)
  File "/home/lpr/.local/lib/python3.7/site-packages/torch/hub.py", line 404, in load
    model = _load_local(repo_or_dir, model, *args, **kwargs)
  File "/home/lpr/.local/lib/python3.7/site-packages/torch/hub.py", line 433, in _load_local
    model = entry(*args, **kwargs)
  File "/home/lpr/.cache/torch/hub/ultralytics_yolov5_master/hubconf.py", line 83, in custom
    return _create(path, autoshape=autoshape, verbose=_verbose, device=device)
  File "/home/lpr/.cache/torch/hub/ultralytics_yolov5_master/hubconf.py", line 33, in _create
    from models.common import AutoShape, DetectMultiBackend
  File "/home/lpr/.cache/torch/hub/ultralytics_yolov5_master/models/common.py", line 28, in <module>
    from utils.dataloaders import exif_transpose, letterbox
  File "/home/lpr/.cache/torch/hub/ultralytics_yolov5_master/utils/dataloaders.py", line 31, in <module>
    from utils.augmentations import (Albumentations, augment_hsv, classify_albumentations, classify_transforms, copy_paste,
  File "/home/lpr/.cache/torch/hub/ultralytics_yolov5_master/utils/augmentations.py", line 15, in <module>
    from utils.general import LOGGER, check_version, colorstr, resample_segments, segment2box, xywhn2xyxy
  File "/home/lpr/.cache/torch/hub/ultralytics_yolov5_master/utils/general.py", line 38, in <module>
    from ultralytics.yolo.utils.checks import check_requirements
ModuleNotFoundError: No module named 'ultralytics'
```

**Comment by AlexGrom1989** [comment]
Have you solved this problem? I have same one
